[Interface]
Address = 10.9.0.8/24
PrivateKey = ""
DNS = 192.168.1.1

PostUp   = iptables -A FORWARD -i wg-home -j ACCEPT; iptables -A FORWARD -o wg-home -j ACCEPT
PostDown = iptables -D FORWARD -i wg-home -j ACCEPT; iptables -D FORWARD -o wg-home -j ACCEPT

[Peer]
PublicKey = ""
Endpoint = 37.205.10.203:51830
AllowedIPs = 10.9.0.0/24
PersistentKeepalive = 25
