[Interface]
Address = 10.9.0.1/24
ListenPort = 51830
PrivateKey = ""

PostUp   = iptables -A FORWARD -i wg-home -j ACCEPT; iptables -A FORWARD -o wg-home -j ACCEPT
PostDown = iptables -D FORWARD -i wg-home -j ACCEPT; iptables -D FORWARD -o wg-home -j ACCEPT

# HOME
[Peer]
PublicKey = ""
AllowedIPs = 10.9.0.2/32, 192.168.1.0/24, 192.168.10.0/24, 192.168.20.0/24, 192.168.30.0/24, 192.168.40.0/24, 192.168.60.0/24

# HOME ASSISTANT
[Peer]
PublicKey = ""
AllowedIPs = 10.9.0.3/32

# STUDIO
[Peer]
PublicKey = ""
AllowedIPs = 10.9.0.4/32

# LAPTOP
[Peer]
PublicKey = ""
AllowedIPs = 10.9.0.5/32

# IPHONE
[Peer]
PublicKey = ""
AllowedIPs = 10.9.0.6/32

# IPAD
[Peer]
PublicKey = ""
AllowedIPs = 10.9.0.7/32
